### ISSUE TITLE
Implement Qdrant support

### ISSUE THREAD

**Issue by kacperlukawski** [psychic-api/psychic#12]
Do you plan to implement Qdrant as another data store? We'd be happy to support that.

**Comment by Ayan-Bandyopadhyay** [comment]
We'll add this to our roadmap!

**Comment by sundar7D0** [comment]
Supporting the famous, open-source milvus vector store will also be helpful. Milvus seems to have some benefits over Weaviate: https://zilliz.com/comparison/milvus-vs-weaviate
