### ISSUE TITLE
Make google drive connector accept a URL instead of a path

### ISSUE THREAD

**Issue by jasonwcfan** [psychic-api/psychic#21]
Right now, the Google Drive connector requires users input a path to the directory they want to ingest. This is unintuitive and prone to error.

Instead, it should accept a URL to the directory. This is much more intuitive for users since they probably already have that folder open in a tab and can simply copy/paste the URL instead of figuring out what the path should be.

We can then parse the URL to determine the ID of the folder.

**Comment by proBhavesh** [comment]
Working on it to solve it.

**Comment by jasonwcfan** [comment]
Thanks @proBhavesh! An update to this issue - we added support for a folder URL already. But it's still not a great experience, I think the ideal would be if the `psychic-modal` project supported the Google Drive file picker (https://developers.google.com/drive/picker/guides/overview) to let users choose the exact files they want.

If you were interested in contributing, this is a great place to start!

**Comment by proBhavesh** [comment]
Thanks @jasonwcfan for the information. I will fix it asap.
