### ISSUE TITLE
How to obtain GDRIVE_CLIENT_SECRETS ?

### ISSUE THREAD

**Issue by sundar7D0** [psychic-api/psychic#24]
In the google-docs data connector, the GDRIVE_CLIENT_SECRETS is read in as environment variable but I am not sure where it's set or to what should a self-hosting user set it to?

Also, as of now, to authenticate using OAuth2, user has to click on "Advanced" and then proceed. But once when you register your google-doc OAuth access endpoint with Google (after which we needn't use the "Advanced" option), will the self-hosting users also get the same benefit but with full data privacy (which is a matter of great concern when dealing with google-drive contents)?

**Comment by sundar7D0** [comment]
Is it obtained through creating some google cloud project for a particular drive account?

**Comment by sundar7D0** [comment]
Any help would be appreciated😅!

**Comment by Ayan-Bandyopadhyay** [comment]
Here is the guide on how to set up the OAuth screen for Google: https://developers.google.com/workspace/guides/auth-overview

**Comment by Ayan-Bandyopadhyay** [comment]
We're also updating our repo to focus more on the oauth connector side of things so we'll have some updated documentation when that's done.

**Comment by sundar7D0** [comment]
It seems like google drive connector in sidekick web demo is not working. It takes to a 3rd party application but doesn't authenticate and says can't connect. Can you update some documentation on it as you have mentioned above on what are the steps?

**Comment by jasonwcfan** [comment]
Hey @sundar7D0 we made some changes recently, you can find the most up to date docs at docs.psychic.dev.

The google drive picker still works, you can go to dashboard.psychic.dev/playground to test it out.
