### ISSUE TITLE
Feature request: Supabase/Postgres datastore

### ISSUE THREAD

**Issue by kiwicopple** [psychic-api/psychic#25]
one of the most common issues we see at supabase is developers getting stuck figuring out how to convert their content to embeddings (so you're working on a valuable problem!)

Would you be interested in adding support for Supabase as a datastore? I think it would help our community a lot. Happy to collaborate on this too.

More context:

- Postgres supports vectors through [pgvector](https://github.com/pgvector/pgvector). 
- Supabase has [support for pgvector](https://supabase.com/blog/openai-embeddings-postgres-vector)

**Comment by egor-romanov** [comment]
ChatGPT Retrieval plugin now supports [Supabase](https://github.com/openai/chatgpt-retrieval-plugin#supabase) and [Postgres](https://github.com/openai/chatgpt-retrieval-plugin#postgres). 
I could help with adding this but i am struggling to find the corresponding logic in the repo, looks like Readme is a bit outdated

**Comment by jasonwcfan** [comment]
Hey @egor-romanov we rebuilt the project recently to focus more on being a universal API for LLM data integration and prprocessing. We haven't added support fort vectorDBs yet in the new version, however we do have a [LangChain document loader](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/psychic.html), so LangChain can be used to integrate Psychic with supabase. We're also adding Psychic as a data loader in LllamaIndex soon too.
