### ISSUE TITLE
Google drive refuses to connect

### ISSUE THREAD

**Issue by dantheman0207** [psychic-api/psychic#67]
I get this error when connecting my account.

![Screenshot 2023-07-26 at 17 08 08](https://github.com/psychic-api/psychic/assets/1239724/dfc944c4-e730-4e77-93dd-1f8586371fec)

This is using Chrome. In Safari I get no error at all, it just hangs while connecting.

**Comment by Ayan-Bandyopadhyay** [comment]
This is happening because we have reached the 100 user limit for an unapproved google drive app. You can get around this by using your own custom credentials for google oauth https://docs.psychic.dev/connectors/gdrive

**Comment by dantheman0207** [comment]
That makes sense! Thanks for letting me know! Big fan so far.
