### ISSUE TITLE
Self-hosted install

### ISSUE THREAD

**Issue by abnerjacobsen** [psychic-api/psychic#68]
Hello,

I would like to test psychic-api locally, on my computer, but I couldn't find a way to create the necessary tables on the Supabase server in the source. How should I go about doing this?

Additionally, what are the environment variables that I have to configure in addition to those needed by Supabase?

Thanks.

**Comment by amitduwal** [comment]
Were you able to host it locally?

**Comment by cameronking4** [comment]
Any luck ?

**Comment by amitduwal** [comment]
> Any luck ?

No . I wasn't able to host it locally. Even when all the parts were properly set it appears to me that the connections were being created from the psychic server. I was unable to resolve it. There is no proper documentation or support available for this repo.
